// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "github.com/fede22/ip2location/internal/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProxyService is a mock of ProxyService interface
type MockProxyService struct {
	ctrl     *gomock.Controller
	recorder *MockProxyServiceMockRecorder
}

// MockProxyServiceMockRecorder is the mock recorder for MockProxyService
type MockProxyServiceMockRecorder struct {
	mock *MockProxyService
}

// NewMockProxyService creates a new mock instance
func NewMockProxyService(ctrl *gomock.Controller) *MockProxyService {
	mock := &MockProxyService{ctrl: ctrl}
	mock.recorder = &MockProxyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProxyService) EXPECT() *MockProxyServiceMockRecorder {
	return m.recorder
}

// GetProxy mocks base method
func (m *MockProxyService) GetProxy(address string) (domain.Proxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxy", address)
	ret0, _ := ret[0].(domain.Proxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxy indicates an expected call of GetProxy
func (mr *MockProxyServiceMockRecorder) GetProxy(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxy", reflect.TypeOf((*MockProxyService)(nil).GetProxy), address)
}

// GetISPs mocks base method
func (m *MockProxyService) GetISPs(countryCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetISPs", countryCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetISPs indicates an expected call of GetISPs
func (mr *MockProxyServiceMockRecorder) GetISPs(countryCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetISPs", reflect.TypeOf((*MockProxyService)(nil).GetISPs), countryCode)
}

// GetIPs mocks base method
func (m *MockProxyService) GetIPs(countryCode string, limit int) ([]domain.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPs", countryCode, limit)
	ret0, _ := ret[0].([]domain.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPs indicates an expected call of GetIPs
func (mr *MockProxyServiceMockRecorder) GetIPs(countryCode, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPs", reflect.TypeOf((*MockProxyService)(nil).GetIPs), countryCode, limit)
}

// GetIPCount mocks base method
func (m *MockProxyService) GetIPCount(countryCode string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPCount", countryCode)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPCount indicates an expected call of GetIPCount
func (mr *MockProxyServiceMockRecorder) GetIPCount(countryCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPCount", reflect.TypeOf((*MockProxyService)(nil).GetIPCount), countryCode)
}

// GetTopProxyTypes mocks base method
func (m *MockProxyService) GetTopProxyTypes(limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopProxyTypes", limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopProxyTypes indicates an expected call of GetTopProxyTypes
func (mr *MockProxyServiceMockRecorder) GetTopProxyTypes(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopProxyTypes", reflect.TypeOf((*MockProxyService)(nil).GetTopProxyTypes), limit)
}
